#!/bin/sh

result1=`cat /proc/stat | sed -n 1p| awk '{print $2+$3+$4+$5+$6+$7+$8+$9}'`
echo ${result1}
idel1=`cat /proc/stat | sed -n 1p| awk '{print $5}'`
echo ${idel1}

sleep 2

result2=`cat /proc/stat | sed -n 1p| awk '{print $2+$3+$4+$5+$6+$7+$8+$9}'`
echo ${result2}
idel2=`cat /proc/stat | sed -n 1p| awk '{print $5}'`
echo ${idel2}

result3=$((result2-result1))
echo ${result3}
idel3=$((idel2-idel1))
echo ${idel3}

pcpu=$((100*(result3-idel3)/result3))
echo "${pcpu}"
printf "%0.2f\n" ${pcpu}
