#!/bin/sh
#
#
begintime=$(date +%Y%m%d%H%M%S)
endtime=$(date +%Y%m%d%H%M%S)
LOGDIR=/audit/sys/log

if [ ! -d ${LOGDIR} ]
then
		mkdir -p ${LOGDIR}
fi
logfile=$LOGDIR/ntpd.log
if [ ! -f $logfile ]
then
		touch $logfile
fi
echo "========begingtime ${begintime}=====">> ${logfile} 2>&1
echo "ntpd service stop" >> ${logfile} 2>&1
/etc/init.d/ntpd stop>> ${logfile} 2>&1
echo "========endtime ${endtime}========">> ${logfile} 2>&1
echo "######################################">> ${logfile} 2>&1
