#!/bin/sh


owcron stop >/dev/null

result=`ps -ef|grep -v grep|grep "owcron start"|awk '{print $2}'`

if [ $result > 1 ]
then
        echo "fail"
else
        owcron start >/dev/null
	result=`ps -ef|grep -v grep|grep "owcron start"|awk '{print $2}'`
	if [ $result > 1 ]
	then
		echo "sucessful"
	else
		echo "fail"
	fi

fi

